spring.application.name=sistema-de-gestion-academico

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_academico
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false

#enable trace mode
#trace=true

#enable debug mode
#debug=true
#logging.level.web=DEBUG

# Enable ansi color output
spring.output.ansi.enabled=ALWAYS

#output log file
#logging.file.name=output.log

# message files config
spring.messages.encoding=UTF-8
spring.messages.basename=exceptions, messages

#enable docker compose in tests
spring.docker.compose.skip.in-tests=false

#java mail sender config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=francotomascallero@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#app url config
app.base-url=http://localhost:8080